/*
  ** Guessing Game **

  Display the message to the user:
  "Guess the number I am thinking of? It is between 0 and 10"

  Create a logic to generate a random number 
  and check if the entered number is the same as the random number generated by the system.

  While the user does not guess the number, show the message:
  "Error, try again:"

  If the user guesses the number, display the message:
  "Congratulations! You guessed the number in x attempts"

  Replace "x" in the message with the number of attempts
*/

// Guessing game

// Displays the message to the user to start the game
let result = prompt('Guess the number I am thinking of? It is between 0 and 10.');

// Generate a random number between 0 and 10
const randomNumber = Math.round(Math.random() * 10);

// Initialize attempt counter
let xAttempts = 1;

// Keep asking the user until they guess the number
while (Number(result) !== randomNumber) {
    result = prompt('Error, try again');
    xAttempts++;
}

// Success message with pluralization of 'attempt' or 'attempts'
alert(`You guessed it, congratulations! The number I was thinking of was ${randomNumber} and you guessed the number in ${xAttempts} attempt${xAttempts > 1 ? 's' : ''}.`);
